### ISSUE TITLE
Can't add more than one metadata

### ISSUE THREAD

**Issue by WendyV** [coveo-labs/web-scraper-helper#17]
Everytime I try to add more than one metadata, it deletes the first element. The "add" button works fine with "Excludes". The problem only occurs with "Metadata".

![webscrapper](https://user-images.githubusercontent.com/17322480/40084851-842405c2-5866-11e8-9ee7-c2703af30fb9.gif)

**Comment by jdevost** [comment]
You need to provide a name for the metadata.

**Comment by WendyV** [comment]
perfect, thank you!
